AppBundle:
    resource: "@AppBundle/Controller/"
    type:     annotation

account_register:
    path:     /register
    defaults: { _controller: AppBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: AppBundle:Account:create }

status_update_create:
    path:     /statusupdate/create
    defaults: { _controller: AppBundle:StatusUpdate:createStatusUpdate }

comment_create:
    path: /comment/{slug}/create
    defaults: { _controller: AppBundle:Comment:create }

logout:
    path: /logout

users:
    path: /users
    defaults: { _controller: AppBundle:AppUser:showUsers }

user_show:
    path: /users/{slug}
    defaults: { _controller: AppBundle:AppUser:showUser }

profile_show:
    path: /profile
    defaults: { _controller: AppBundle:Profile:showProfile }

profilepic_upload:
    path: /profilepic/upload
    defaults: { _controller: AppBundle:Profile:uploadProfilePic }

profile_edit:
    path: /profile/edit
    defaults: { _controller: AppBundle:Profile:editProfile }

password_change:
    path: /password/change
    defaults: { _controller: AppBundle:Profile:changePassword }

groups:
    path: /groups
    defaults: { _controller: AppBundle:AppGroup:showAppGroups }

group_show:
    path: /groups/{slug}
    defaults: { _controller: AppBundle:AppGroup:showAppGroup }

group_create:
    path: /group/create
    defaults: { _controller: AppBundle:AppGroup:createAppGroup }

group_members:
    path: /groups/{slug}/members
    defaults: { _controller: AppBundle:AppGroup:showAppGroupMembers }

group_update_create:
    path: /groups/{slug}/updates/create
    defaults: { _controller: AppBundle:AppGroupUpdate:createAppGroupUpdate }

crops:
    path: /crops
    defaults: { _controller: AppBundle:Crop:showCrops }

crop_show:
    path: /crops/{slug}
    defaults: { _controller: AppBundle:Crop:showCrop }

crop_growers:
    path: /crops/{slug}/growers
    defaults: { _controller: AppBundle:Crop:showCropGrowers }

friends:
    path: /users/{slug}/friends
    defaults: { _controller: AppBundle:Friend:showFriends }

friend_show:
    path: /friends/{slug}
    defaults: {_controller: AppBundle:Friend:showFriend }

friendrequests:
    path: /friendrequests
    defaults: { _controller: AppBundle:FriendRequest:showFriendRequests }

sentfriendrequests:
    path: /sentfriendrequests
    defaults: { _controller: AppBundle:FriendRequest:showSentFriendRequests }

users_groups:
    path: /users/{slug}/groups
    defaults: { _controller: AppBundle:AppGroup:showUsersGroups }

users_crops:
    path: /users/{slug}/crops
    defaults: { _controller: AppBundle:Crop:showUsersCrops }

users_info:
    path: /users/{slug}/info
    defaults: { _controller: AppBundle:AppUser:ShowUserInfo }

requestform:
    path:  /users/{slug}/createrequest
    defaults: { _controller: AppBundle:FriendRequest:createFriendRequest }

acceptrequestform:
    path:  /users/{slug}/acceptrequest
    defaults: { _controller: AppBundle:FriendRequest:acceptFriendRequest }

deletefriendform:
    path:  /users/{slug}/deletefriend
    defaults: { _controller: AppBundle:Friend:deleteFriend }




