app:
    resource: "@AppBundle/Controller/"
    type:     annotation

account_register:
    path:     /register
    defaults: { _controller: AppBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: AppBundle:Account:create }

status_update_register:
    path:     /statusupdate/register
    defaults: { _controller: AppBundle:StatusUpdate:registerStatusUpdate }

status_update_create:
    path:     /statusupdate/create
    defaults: { _controller: AppBundle:StatusUpdate:createStatusUpdate }

comment_create:
    path: /comment/{slug}/create
    defaults: { _controller: AppBundle:Comment:create }

logout:
    path: /logout

locations:
    path: /locations
    defaults: { _controller: AppBundle:Location:showLocations }

location_show:
    path: /locations/{slug}
    defaults: { _controller: AppBundle:Location:showLocation }

users:
    path: /users
    defaults: { _controller: AppBundle:AppUser:showUsers }

user_show:
    path: /users/{slug}
    defaults: { _controller: AppBundle:AppUser:showUser }

groups:
    path: /groups
    defaults: { _controller: AppBundle:AppGroup:showAppGroups }

group_show:
    path: /groups/{slug}
    defaults: { _controller: AppBundle:AppGroup:showAppGroup }

group_register:
    path: /group/register
    defaults: { _controller: AppBundle:AppGroup:registerAppGroup }

group_create:
    path: /group/create
    defaults: { _controller: AppBundle:AppGroup:createAppGroup }

crops:
    path: /crops
    defaults: { _controller: AppBundle:Crop:showCrops }

crop_show:
    path: /crops/{slug}
    defaults: { _controller: AppBundle:Crop:showCrop }

friends:
    path: /users/{slug}/friends
    defaults: { _controller: AppBundle:Friend:showFriends }

friendrequests:
    path: /users/{slug}/friendrequests
    defaults: { _controller: AppBundle:FriendRequest:showFriendRequests }

sentfriendrequests:
    path: /users/{slug}/sentfriendrequests
    defaults: { _controller: AppBundle:FriendRequest:showSentFriendRequests }

users_groups:
    path: /users/{slug}/groups
    defaults: { _controller: AppBundle:AppGroup:showUsersGroups }

users_crops:
    path: /users/{slug}/crops
    defaults: { _controller: AppBundle:Crop:showUsersCrops }

requestform:
    path:  /users/{slug}/createrequest
    defaults: { _controller: AppBundle:FriendRequest:createFriendRequest }

acceptrequestform:
    path:  /users/{slug}/acceptrequest
    defaults: { _controller: AppBundle:FriendRequest:acceptFriendRequest }

deletefriendform:
    path:  /users/{slug}/deletefriend
    defaults: { _controller: AppBundle:Friend:deleteFriend }




