# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    kernel.listener.cache_listener:
        class: AppBundle\EventListener\CacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    kernel.listener.last_route_listener:
        class: AppBundle\EventListener\LastRouteListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 30 }